#!/usr/bin/env bash

set -e

DEBUG=${DEBUG:-false}
MONGODB_AUTH_DB=${MONGODB_AUTH_DB:-admin}
BACKUP_DATE_FORMAT="${BACKUP_DATE_FORMAT:-+%Y%m%d-%H%M}"
BACKUP_NAME="${MONGODB_DATABASE:?}-$(date "${BACKUP_DATE_FORMAT:?}")"

declare aws_s3_extra_args=''

if [[ "${DEBUG}" == 'true' ]]; then
  aws_s3_extra_args='--debug'
fi

echo "Dumping database ${MONGODB_DATABASE:?} using mongodump"
mongodump --ssl --username "${MONGODB_USERNAME:?}" --password "${MONGODB_PASSWORD:?}" --authenticationDatabase "${MONGODB_AUTH_DB}" --db "${MONGODB_DATABASE:?}" "${MONGODB_CONNECTION:?}"

sleep 5

echo "Uploading database dump to S3"
aws s3 cp ${aws_s3_extra_args} --recursive "/dump/${MONGODB_DATABASE:?}/" "s3://${AWS_S3_BACKUP_BUCKET:?}/${AWS_S3_BACKUP_PREFIX}${BACKUP_NAME:?}"

if [[ "${WEBHOOK_URL}" != "" ]]; then
  echo "Invoking webhook (${WEBHOOK_URL:?})"
  curl --retry 3 "${WEBHOOK_URL:?}"
  echo
fi

echo "Backup completed"
